# Instructions

- This homework assignment is worth **51** points. 
- Please strive for clarity and organization.
- **AI Usage**:
   - AI use is strictly **prohibited** for conceptual exercises.
   - For applied (Python) exercises, you may only use AI for **debugging**. Do not use AI to generate answers.
- **Due Date: September 18, 2026, by 11:59 PM.**

# Exercise 1 

In this exercise, we will keep practicing basic operations with `pandas`. 

### Exercise 1(a) (2 points)

Import the `pandas` library.

In [1]:
import pandas as pd

### Exercise 1(b) (3 points)

Create a data-frame called `euro12` using the data from `Euro_2012_stats_TEAM.csv`.

In [4]:
euro12 = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro12.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

### Exercise 1(c) (2 points)

Compute the average number of `Goals`.

In [5]:
euro12["Goals"].mean()

np.float64(4.75)

### Exercise 1(d) (2 points)

How many teams participated in the Euro 2012?

In [6]:
euro12["Team"].nunique()# Your answer here

16

### Exercise 1(e) (3 points)

Create a data-frame called `discipline` using `Team`, `Yellow Cards`, and `Red Cards` from the `euro12` data-frame.

In [10]:
discipline = euro12[["Team", "Yellow Cards", "Red Cards"]]
discipline

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

### Exercise 1(f) (3 points)

Sort the `discipline` data-frame based on `Red Cards`.

In [11]:
discipline.sort_values(by="Red Cards")

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
7                 Italy            16          0
8           Netherlands             5          0
14               Sweden             7          0
10             Portugal            12          0
13                Spain            11          0
12               Russia             6          0
15              Ukraine             5          0
6                Greece             9          1
11  Republic of Ireland             6          1
9                Poland             7          1

### Exercise 1(g) (3 points)

Using the `discipline`, compute the average number of `Yellow Cards`.

In [12]:
discipline["Yellow Cards"].mean()

np.float64(7.4375)

### Exercise 1(h) (3 points)

Using the `euro12` data-frame, report the team that scored more than 6 goals.

In [13]:
euro12[euro12["Goals"] > 6]["Team"]

5     Germany
13      Spain
Name: Team, dtype: str

### Exercise 1(i) (3 points)

Using the `euro12` data-frame, report the teams that start with `S`.

In [14]:
euro12[euro12["Team"].str.startswith("S")]["Team"]

13     Spain
14    Sweden
Name: Team, dtype: str

# Exercise 2 (10 points)

In this exercise, you will use the `Raisin_Dataset.csv`. For more details about the dataset, see this [link](https://www.kaggle.com/datasets/nimapourmoradi/raisin-binary-classification/data).
Here's a practical exercise highlighting modularity's importance in data science by refactoring non-modular code into modular, reusable components. You are given a simple data science task: load a dataset, clean it, perform some feature engineering, train a machine learning model, and evaluate the results. However, the initial code is not modular—it is repetitive and hard to maintain.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Load dataset
df = pd.read_csv('Raisin_Dataset.csv')

# # Clean dataset
df = df.dropna()
df['Area/Perimeter'] = df['Area'] / df['Perimeter']
df['sqrt_area'] = np.sqrt(df['Area'])
df['ext/ecc'] = df['Extent'] / df['Eccentricity']
df['convA/Area'] = df['ConvexArea'] / df['Area']
df['Class'] = df['Class'].map({'Besni':0, 'Kecimen':1})

# Split dataset into training and testing
X = df.drop(columns='Class', axis=1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

This script works, but it's not modular. If you needed to modify the data-cleaning process or change the model, you’d have to go through the whole script and make changes in several places. Now, refactor the code into modular, reusable components by turning each logical part into functions. This modular design will make it easier to maintain, test, and reuse for different datasets or models.

In [17]:
def load_data(file):
    return pd.read_csv(file)

def clean_data(df):
    df = df.dropna()
    df['Area/Perimeter'] = df['Area'] / df['Perimeter']
    df['sqrt_area'] = np.sqrt(df['Area'])
    df['ext/ecc'] = df['Extent'] / df['Eccentricity']
    df['convA/Area'] = df['ConvexArea'] / df['Area']
    df['Class'] = df['Class'].map({'Besni': 0, 'Kecimen': 1})
    return df

def split_data(df):
    X = df.drop(columns='Class')
    y = df['Class']
    return train_test_split(X, y, test_size=0.2, random_state=42)

def train_model(X_train, y_train):
    model = RandomForestClassifier()
    model.fit(X_train, y_train)
    return model

def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

df = load_data("Raisin_Dataset.csv")
df = clean_data(df)

X_train, X_test, y_train, y_test = split_data(df)

model = train_model(X_train, y_train)

accuracy = evaluate_model(model, X_test, y_test)

print(f"Accuracy: {accuracy}")

Accuracy: 0.8555555555555555

# Exercise 3 (8 points)

In this exercise, you will time all the component of your answer from Exercise 2. Report the times. 

1. Which part of the code is the bottleneck?
2. What would happen if the dataset grew in size? Would certain parts of the code scale efficiently, or would they slow down significantly?

In [18]:
import time

start = time.time()
df = load_data("Raisin_Dataset.csv")
print("Load data:", time.time() - start)

start = time.time()
df = clean_data(df)
print("Clean data:", time.time() - start)

start = time.time()
X_train, X_test, y_train, y_test = split_data(df)
print("Split data:", time.time() - start)

start = time.time()
model = train_model(X_train, y_train)
print("Train model:", time.time() - start)

start = time.time()
accuracy = evaluate_model(model, X_test, y_test)
print("Evaluate model:", time.time() - start)

Load data: 0.002602815628051758
Clean data: 0.0027256011962890625
Split data: 0.0017547607421875
Train model: 0.16051435470581055
Evaluate model: 0.008803606033325195

1. Model training was the bottleneck because it took 16 seconds, which was much longer than everything else.

2. If the dataset got bigger, all parts of the code would probably take a little longer, but some would handle the increase better than others. Loading, cleaning, and splitting the data are running pretty quickly right now, so I would expect those to scale more efficiently. The model training would probably slow down more significantly because it already takes much longer than the other parts of the code.

# Exercise 4 (9 points)

The following questions are conceptual. Answer them in your own words, in complete sentences. **No AI use is permitted for these questions.**

### Exercise 4(a) (3 points)

In your own words, explain the *Don't Repeat Yourself* (DRY) principle. Using the code from Exercise 2 as your example, identify one place where repetition (or near-repetition) occurs and explain what problem would arise later if that repeated logic had to change.

 The DRY principle means “Don’t Repeat Yourself.” So, if you use the same or similar code multiple times, it is better to turn it into a function instead of rewriting it over and over. I think this happens in Exercise 2 with the data cleaning and feature engineering, where we create new columns using existing columns. We have also done this in class. If we repeated that same logic in different places and later needed to change it, I would have to go back and make sure I changed it everywhere. Functions make the code easier to update and help prevent mistakes, like changing one section but forgetting to change another.

### Exercise 4(b) (3 points)

A classmate says: "My script runs and gives the right answer, so the code is good." Using at least three of the five principles of good code (simplicity, modularity, readability, performance, robustness), explain why producing the correct output is not enough to call code good.

I don’t think code is automatically good just because it runs and gives the right answer. It also needs to be readable, organized, and able to perform well. Readability is important because someone else should be able to look at the code and understand what I was trying to do. Modularity also matters because breaking the code into functions makes it easier to change or reuse parts without rewriting everything. Performance matters too, especially as the dataset grows. Code that runs quickly with a small dataset might take much longer with a larger one. So, getting the right answer matters, but good code should also be easy to understand, update, and reuse.

### Exercise 4(c) (3 points)

Suppose the `Raisin_Dataset.csv` file used in Exercise 2 is missing a few values in the `Area` column, and later the file is renamed. Explain what *robustness* means in this context, and describe two specific things you would add to your Exercise 2 functions so that the program does not fail silently. In your answer, explain the difference between an inline comment and a docstring, and state which one you would use to document the behavior you added.

Robustness means the program can handle problems without failing and without explaining what went wrong. In Exercise 2, I would first check for missing values in the column before using it to create any new features. I would also add error handling when loading Raisin_Dataset.csv, so if the file was renamed or could not be found, the program would give a clear message explaining the problem. An inline comment is a short explanation of a specific line or section of code, while a docstring explains what a function does and how it is supposed to work. For these changes, I would use a docstring because I want someone using the function to know how it handles missing data or file problems.